# Welcome to Jekyll!
#

# Site settings
title: Full Bars Media
description: |
  Connect, Better.
owner: Fullbarsmedia.com # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: alex@thealexmorris.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fullbarsmedia.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/fullbarsmedia
  linkedin-square: https://linkedin.com/company/fullbarsmedia
  facebook-official: https://www.facebook.com/Fullbarsmedia-213281409368250/
destination: ./docs/
include: ['./_extra/CNAME', './css/*']


# Build settings
markdown: kramdown
#sass:
#  style: compressed
