# Welcome to Jekyll!
#

# Site settings
title: FullBarsMedia
description: |
  Connect, Better.
owner: Fullbarsmedia.com # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: alex@thealexmorris.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fullbarsmedia.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
destination: ./docs/
include: ./_extra/CNAME

# Build settings
markdown: kramdown
#sass:
#  style: compressed
